#pragma once

#define wl_display_interface                      _awin_wl_display_interface
#define wl_subcompositor_interface                _awin_wl_subcompositor_interface
#define wl_compositor_interface                   _awin_wl_compositor_interface
#define wl_shm_interface                          _awin_wl_shm_interface
#define wl_data_device_manager_interface          _awin_wl_data_device_manager_interface
#define wl_shell_interface                        _awin_wl_shell_interface
#define wl_buffer_interface                       _awin_wl_buffer_interface
#define wl_callback_interface                     _awin_wl_callback_interface
#define wl_data_device_interface                  _awin_wl_data_device_interface
#define wl_data_offer_interface                   _awin_wl_data_offer_interface
#define wl_data_source_interface                  _awin_wl_data_source_interface
#define wl_keyboard_interface                     _awin_wl_keyboard_interface
#define wl_output_interface                       _awin_wl_output_interface
#define wl_pointer_interface                      _awin_wl_pointer_interface
#define wl_region_interface                       _awin_wl_region_interface
#define wl_registry_interface                     _awin_wl_registry_interface
#define wl_seat_interface                         _awin_wl_seat_interface
#define wl_shell_surface_interface                _awin_wl_shell_surface_interface
#define wl_shm_pool_interface                     _awin_wl_shm_pool_interface
#define wl_subsurface_interface                   _awin_wl_subsurface_interface
#define wl_surface_interface                      _awin_wl_surface_interface
#define wl_touch_interface                        _awin_wl_touch_interface
#define zwp_idle_inhibitor_v1_interface           _awin_zwp_idle_inhibitor_v1_interface
#define zwp_idle_inhibit_manager_v1_interface     _awin_zwp_idle_inhibit_manager_v1_interface
#define zwp_confined_pointer_v1_interface         _awin_zwp_confined_pointer_v1_interface
#define zwp_locked_pointer_v1_interface           _awin_zwp_locked_pointer_v1_interface
#define zwp_pointer_constraints_v1_interface      _awin_zwp_pointer_constraints_v1_interface
#define zwp_relative_pointer_v1_interface         _awin_zwp_relative_pointer_v1_interface
#define zwp_relative_pointer_manager_v1_interface _awin_zwp_relative_pointer_manager_v1_interface
#define wp_viewport_interface                     _awin_wp_viewport_interface
#define wp_viewporter_interface                   _awin_wp_viewporter_interface
#define xdg_toplevel_interface                    _awin_xdg_toplevel_interface
#define zxdg_toplevel_decoration_v1_interface     _awin_zxdg_toplevel_decoration_v1_interface
#define zxdg_decoration_manager_v1_interface      _awin_zxdg_decoration_manager_v1_interface
#define xdg_popup_interface                       _awin_xdg_popup_interface
#define xdg_positioner_interface                  _awin_xdg_positioner_interface
#define xdg_surface_interface                     _awin_xdg_surface_interface
#define xdg_toplevel_interface                    _awin_xdg_toplevel_interface
#define xdg_wm_base_interface                     _awin_xdg_wm_base_interface
#define xdg_activation_v1_interface               _awin_xdg_activation_v1_interface
#define xdg_activation_token_v1_interface         _awin_xdg_activation_token_v1_interface
#define wl_surface_interface                      _awin_wl_surface_interface
#define wp_fractional_scale_v1_interface          _awin_wp_fractional_scale_v1_interface